FROM node:24 AS build-stage
WORKDIR /usr/src/app

COPY . .

ARG VITE_BASE_URL
ARG VITE_IMGIX_BASE_URL

RUN npm ci
RUN npm run build

FROM nginx:1.29-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
