version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5500:5432
    expose:
      - 5500
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "postgres"
