version: "3.9"

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: /movies
  db:
    image: postgres
    restart: always
    ports:
      - 5500:5432
    expose:
      - 5500
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "postgres"
