version: "3.9"

services:
  db:
    image: postgres
    container_name: movieDB
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "testDB"
      POSTGRES_USER: "user"

  server:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://user:pass@movieDB:5432/testDB?sslmode=disable
      ENV: "docker"
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - .:/app
    command: ./server
    depends_on:
      - db
